#import <Foundation/Foundation.h>
#import "SWGUserInfo.h"
#import "SWGError.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGCustomerApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGCustomerApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGCustomerApi*) sharedAPI;
///
///
/// associate user information
/// associate information.
///
/// @param wbUserId 
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) associateUserWithWeiboIdGetWithCompletionBlock :(NSString*) wbUserId 
    
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error))completionBlock;
    


///
///
/// update user birthday
/// user information.
///
/// @param userId 
/// @param userBirthday 
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) updateUserBirthdayGetWithCompletionBlock :(NSString*) userId 
     userBirthday:(NSString*) userBirthday 
    
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error))completionBlock;
    


///
///
/// update user name
/// user information.
///
/// @param userId 
/// @param userName 
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) updateUserNameGetWithCompletionBlock :(NSString*) userId 
     userName:(NSString*) userName 
    
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error))completionBlock;
    


///
///
/// get user information
/// user information.
///
/// @param userId 
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) userByIdGetWithCompletionBlock :(NSString*) userId 
    
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error))completionBlock;
    


///
///
/// get user information
/// user information.
///
/// @param wbUserId 
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) userByWeiboIdGetWithCompletionBlock :(NSString*) wbUserId 
    
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error))completionBlock;
    



@end
