#import <Foundation/Foundation.h>
#import "SWGError.h"
#import "SWGTokenInfo.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGFileApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGFileApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGFileApi*) sharedAPI;
///
///
/// qiniu uoload token
/// get qiniu upload token.
///
/// 
///
/// @return SWGTokenInfo*
-(NSNumber*) uploadTokenGetWithCompletionBlock :
    (void (^)(SWGTokenInfo* output, NSError* error))completionBlock;
    



@end
