#import <Foundation/Foundation.h>
#import "SWGPhotoInfo.h"
#import "SWGError.h"
#import "SWGAlbumInfo.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGIAlbumApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGIAlbumApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGIAlbumApi*) sharedAPI;
///
///
/// add photo to album
/// add photo to album.
///
/// @param albumId 
/// @param photoName 
/// @param photoUrl 
/// 
///
/// @return SWGPhotoInfo*
-(NSNumber*) addPhotoToAlbumGetWithCompletionBlock :(NSString*) albumId 
     photoName:(NSString*) photoName 
     photoUrl:(NSString*) photoUrl 
    
    completionHandler: (void (^)(SWGPhotoInfo* output, NSError* error))completionBlock;
    


///
///
/// get album info by id
/// album information.
///
/// @param albumId 
/// 
///
/// @return SWGAlbumInfo*
-(NSNumber*) albumByIdGetWithCompletionBlock :(NSString*) albumId 
    
    completionHandler: (void (^)(SWGAlbumInfo* output, NSError* error))completionBlock;
    


///
///
/// get all user albums
/// album information.
///
/// @param userId 
/// 
///
/// @return NSArray<SWGAlbumInfo>*
-(NSNumber*) allAlbumsGetWithCompletionBlock :(NSString*) userId 
    
    completionHandler: (void (^)(NSArray<SWGAlbumInfo>* output, NSError* error))completionBlock;
    


///
///
/// create a new album
/// create album.
///
/// @param userId 
/// @param albumName 
/// @param albumDesc 
/// @param cover 
/// 
///
/// @return SWGAlbumInfo*
-(NSNumber*) createAlbumGetWithCompletionBlock :(NSString*) userId 
     albumName:(NSString*) albumName 
     albumDesc:(NSString*) albumDesc 
     cover:(NSString*) cover 
    
    completionHandler: (void (^)(SWGAlbumInfo* output, NSError* error))completionBlock;
    


///
///
/// get all photos in album
/// all photos in album.
///
/// @param albumId 
/// 
///
/// @return NSArray<SWGPhotoInfo>*
-(NSNumber*) photosInAlbumGetWithCompletionBlock :(NSString*) albumId 
    
    completionHandler: (void (^)(NSArray<SWGPhotoInfo>* output, NSError* error))completionBlock;
    



@end
