#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPhotoInfo
@end

@interface SWGPhotoInfo : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* desc;

@property(nonatomic) NSString* url;

@property(nonatomic) NSDate* created;

@property(nonatomic) NSDate* modified;

@end
