#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserInfo
@end

@interface SWGUserInfo : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* birthday;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* weiboId;

@property(nonatomic) NSString* weiboToken;

@property(nonatomic) NSString* avatarKey;

@property(nonatomic) NSString* avatarHash;

@property(nonatomic) NSDate* created;

@property(nonatomic) NSDate* modified;

@end
